add_newline = true

format = """
‚ï≠‚îÄ $os$username$hostname$directory$fill$jobs$cmd_duration$rust$nodejs$shell
‚ï∞‚îÄ$character
"""

# ---------------- OS ----------------
[os]
format = "[$symbol ]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Arch = "ÔåÉ"

# ---------------- USER / HOST ----------------
[username]
format = "[$user]($style)"
style_user = "bold purple"
show_always = true

[hostname]
format = "[|>$hostname ]($style)"
style = "bold purple"
ssh_only = false

# ---------------- DIRECTORY ----------------
[directory]
format = "[ÔÅº $path ]($style)"
style = "bold blue"
truncation_length = 4
truncation_symbol = "‚Ä¶/"
truncate_to_repo = false

# ---------------- FILL (push right side) ----------------
[fill]
symbol = " "

# ---------------- CMD DURATION ----------------
[cmd_duration]
format = "[Ôâí $duration ]($style)"
style = "bold green"
min_time = 1000

# ---------------- LANG RUNTIMES (auto show) ----------------
[rust]
format = "[Óöã $version ]($style)"
style = "bold red"

[nodejs]
format = "[Û∞éô $version ]($style)"
style = "bold green"

[bun]
symbol = "ü•ü "
format = "[$symbol]($style)"

[lua]
symbol = "üåô "
format = "[$symbol]($style)"

# ---------------- JOBS (auto show) ----------------
[jobs]
symbol = "Û∞Üç "
format = "[$symbol$number]($style) "
style = "bold magenta"

# ---------------- Shell Icon ----------------
[shell]
disabled = false
format = "[$indicator $shell ]($style)"
style = "bold yellow"

bash_indicator = "ÓØä Bash"
zsh_indicator  = "ÔÑ† zsh"
fish_indicator = "Û∞à∫ "
nu_indicator   = "Û∞Ñõ "
powershell_indicator = "Û∞®ä"
unknown_indicator = "?"

# ---------------- PROMPT SYMBOL ----------------
[character]
success_symbol = "[‚ùØ](bold green)"
error_symbol = "[‚ùØ](bold red)"
